version: '3'
services:
  mysql_container:
    image: mysql:latest
    container_name: apache_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - ./mysql/data:/var/lib/mysql
    networks:
      - apache_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  order_server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: apache_order_server
    ports:
        - "50000:50000"
    depends_on:
      mysql_container:
        condition: service_healthy
    networks:
      - apache_network
    environment:
      - PYRO_SERIALIZERS_ACCEPTED=serpent,json,marshal,pickle
      - PYRO_SOCK_REUSE=True
      - PYRO_REUSE_ADDR=True

  order_client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    container_name: apache_order_client
    ports:
      - "8089:8089"
    depends_on:
      - order_server
    networks:
      - apache_network
    stdin_open: true
    tty: true
    environment:
      - PYRO_SERIALIZERS_ACCEPTED=serpent,json,marshal,pickle
      - PYRO_SOCK_REUSE=True
      - PYRO_REUSE_ADDR=True
      - THRIFT_SERVER=order_server
      - THRIFT_PORT=50000
#    command: locust -f /app/locustfile.py --host=http://order_server --web-port=8089

networks:
  apache_network:
    driver: bridge

volumes:
  mysql_data: