version: '3'
services:
  mysql_container:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    volumes:
      - .mysql/data:/var/lib/mysql
    networks:
      - order_network
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  order_server:
    build:
      context: ./server
    container_name: order_server
    depends_on:
      mysql_container:
        condition: service_healthy
    networks:
      - order_network
    environment:
      - PYRO_SERIALIZERS_ACCEPTED=serpent,json,marshal,pickle
      - PYRO_SOCK_REUSE=True
      - PYRO_REUSE_ADDR=True
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 8G

  order_client:
    build:
      context: ./client
    container_name: order_client
    ports:
      - "8089:8089"
    depends_on:
      - order_server
    networks:
      - order_network
    stdin_open: true
    tty: true
    environment:
      - PYRO_SERIALIZERS_ACCEPTED=serpent,json,marshal,pickle
      - PYRO_SOCK_REUSE=True
      - PYRO_REUSE_ADDR=True
    command: locust -f /app/locustfile.py --host=http://order_server --web-port=8089

networks:
  order_network:
    driver: bridge

volumes:
  mysql_data: